# Generated by Django 2.2.1 on 2019-05-18 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('vote_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('yes_votes', models.IntegerField(blank=True, null=True)),
                ('no_votes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
